// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0T9kncy1z7Hql-rVgx0NGRc6Ywn1C85k',
    appId: '1:781960455917:web:242954e5877bd1e1888ee4',
    messagingSenderId: '781960455917',
    projectId: 'aichat-c0c27',
    authDomain: 'aichat-c0c27.firebaseapp.com',
    storageBucket: 'aichat-c0c27.firebasestorage.app',
    measurementId: 'G-QQLHLL4556',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTZxDtZxeUMEbvY6IqAkgoOoSZvRBoQ0',
    appId: '1:781960455917:android:15f4f65f70447749888ee4',
    messagingSenderId: '781960455917',
    projectId: 'aichat-c0c27',
    storageBucket: 'aichat-c0c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-ifAAVntlPJbf-YthjOVGsYbng83xNk',
    appId: '1:781960455917:ios:8fb39badc61ee4a2888ee4',
    messagingSenderId: '781960455917',
    projectId: 'aichat-c0c27',
    storageBucket: 'aichat-c0c27.firebasestorage.app',
    iosBundleId: 'dev.buildwithai.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-ifAAVntlPJbf-YthjOVGsYbng83xNk',
    appId: '1:781960455917:ios:8fb39badc61ee4a2888ee4',
    messagingSenderId: '781960455917',
    projectId: 'aichat-c0c27',
    storageBucket: 'aichat-c0c27.firebasestorage.app',
    iosBundleId: 'dev.buildwithai.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVhZZnNIrBq5xKwMYx4yH9KDmg6lOME5c',
    appId: '1:468507853424:windows:8d9c54b0f5a6a7db9a4e2f',
    messagingSenderId: '468507853424',
    projectId: 'aichat-c0c27',
    authDomain: 'aichat-c0c27.firebaseapp.com',
    storageBucket: 'aichat-c0c27.firebasestorage.app',
  );
}